"""empty message

Revision ID: 19305750d303
Revises: a7df352c8d81
Create Date: 2024-02-16 22:51:04.738765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19305750d303'
down_revision: Union[str, None] = 'a7df352c8d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user_trainings', sa.Column('sets', sa.INTEGER(), nullable=True))
    op.add_column('t_user_trainings', sa.Column('reps', sa.INTEGER(), nullable=True))
    op.add_column('t_user_trainings', sa.Column('kg', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user_trainings', 'kg')
    op.drop_column('t_user_trainings', 'reps')
    op.drop_column('t_user_trainings', 'sets')
    # ### end Alembic commands ###
