"""empty message

Revision ID: 2031a9c5d087
Revises: 67c2f099ae4e
Create Date: 2024-02-03 10:20:44.171277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2031a9c5d087'
down_revision: Union[str, None] = '67c2f099ae4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user_calendars',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('training_plan_id', sa.INTEGER(), nullable=True),
    sa.Column('calendar_comment', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['t_training_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user_calendars')
    # ### end Alembic commands ###
