"""empty message

Revision ID: 207a1528e5c7
Revises: 882737fe3c68
Create Date: 2024-02-02 19:29:51.187145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207a1528e5c7'
down_revision: Union[str, None] = '882737fe3c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_no', sa.INTEGER(), nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_comment', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_no')
    )
    op.create_table('m_parts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_no', sa.INTEGER(), nullable=False),
    sa.Column('part_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sub_part_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('part_comment', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_no')
    )
    op.create_table('m_purposes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purpose_no', sa.INTEGER(), nullable=False),
    sa.Column('purpose_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('purpose_comment', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose_no')
    )
    op.create_table('m_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type_no', sa.INTEGER(), nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type_comment', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_no')
    )
    op.create_table('m_trainings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('training_no', sa.INTEGER(), nullable=False),
    sa.Column('training_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('purpose_no', sa.INTEGER(), nullable=True),
    sa.Column('part_no', sa.INTEGER(), nullable=True),
    sa.Column('type_no', sa.INTEGER(), nullable=True),
    sa.Column('event_no', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['event_no'], ['m_events.event_no'], ),
    sa.ForeignKeyConstraint(['part_no'], ['m_parts.part_no'], ),
    sa.ForeignKeyConstraint(['purpose_no'], ['m_purposes.purpose_no'], ),
    sa.ForeignKeyConstraint(['type_no'], ['m_types.type_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_no')
    )
    op.create_table('t_user_trainings',
    sa.Column('training_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('training_no', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.ForeignKeyConstraint(['training_no'], ['m_trainings.training_no'], ),
    sa.ForeignKeyConstraint(['training_plan_id'], ['t_training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('m_type')
    op.drop_table('m_event')
    op.drop_table('m_part')
    op.drop_table('m_purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_purpose',
    sa.Column('purpose_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('purpose_comment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purpose_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('purpose_no', name='m_purpose_purpose_no_key')
    )
    op.create_table('m_part',
    sa.Column('part_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sub_part_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('part_comment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('part_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('part_no', name='m_part_part_no_key')
    )
    op.create_table('m_event',
    sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_comment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('event_no', name='m_event_event_no_key')
    )
    op.create_table('m_type',
    sa.Column('type_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type_comment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('type_no', name='m_type_type_no_key')
    )
    op.drop_table('t_user_trainings')
    op.drop_table('m_trainings')
    op.drop_table('m_types')
    op.drop_table('m_purposes')
    op.drop_table('m_parts')
    op.drop_table('m_events')
    # ### end Alembic commands ###
