"""empty message

Revision ID: 67c2f099ae4e
Revises: 0d9d1f8f5be9
Create Date: 2024-02-02 19:40:43.965073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c2f099ae4e'
down_revision: Union[str, None] = '0d9d1f8f5be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
