"""empty message

Revision ID: 80a9c4f2cb40
Revises: 7b8356212001
Create Date: 2024-01-25 19:00:25.827638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a9c4f2cb40'
down_revision: Union[str, None] = '7b8356212001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_users', 'postal_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_users', 'postal_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
