"""empty message

Revision ID: 882737fe3c68
Revises: 920ef65efc27
Create Date: 2024-02-02 19:20:46.397274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882737fe3c68'
down_revision: Union[str, None] = '920ef65efc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_trainings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('training_no', sa.INTEGER(), nullable=False),
    sa.Column('training_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('purpose_no', sa.INTEGER(), nullable=True),
    sa.Column('part_no', sa.INTEGER(), nullable=True),
    sa.Column('type_no', sa.INTEGER(), nullable=True),
    sa.Column('event_no', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['event_no'], ['m_event.event_no'], ),
    sa.ForeignKeyConstraint(['part_no'], ['m_part.part_no'], ),
    sa.ForeignKeyConstraint(['purpose_no'], ['m_purpose.purpose_no'], ),
    sa.ForeignKeyConstraint(['type_no'], ['m_type.type_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_no')
    )
    op.create_table('t_user_trainings',
    sa.Column('training_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('training_no', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.ForeignKeyConstraint(['training_no'], ['m_trainings.training_no'], ),
    sa.ForeignKeyConstraint(['training_plan_id'], ['t_training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user_trainings')
    op.drop_table('m_trainings')
    # ### end Alembic commands ###
