"""empty message

Revision ID: 920ef65efc27
Revises: 39349986d8a5
Create Date: 2024-02-02 19:20:11.484160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920ef65efc27'
down_revision: Union[str, None] = '39349986d8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_effectiveness')
    op.drop_table('m_difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_difficulty',
    sa.Column('difficulty_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('difficulty_no', name='m_difficulty_difficulty_no_key')
    )
    op.create_table('m_effectiveness',
    sa.Column('effectiveness_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effectiveness_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effectiveness_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('effectiveness_no', name='m_effectiveness_effectiveness_no_key')
    )
    # ### end Alembic commands ###
