"""empty message

Revision ID: 928117998999
Revises: 9377ee8d4c30
Create Date: 2024-01-29 15:24:43.470701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928117998999'
down_revision: Union[str, None] = '9377ee8d4c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_notifications', 'type',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_notifications', 'type',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
