"""empty message

Revision ID: 9377ee8d4c30
Revises: 80a9c4f2cb40
Create Date: 2024-01-29 15:24:04.383169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9377ee8d4c30'
down_revision: Union[str, None] = '80a9c4f2cb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_notifications', sa.Column('type', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_notifications', 'type')
    # ### end Alembic commands ###
