"""empty message

Revision ID: 9b24d18638ba
Revises: 19305750d303
Create Date: 2024-02-16 23:07:37.035347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b24d18638ba'
down_revision: Union[str, None] = '19305750d303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user_trainings', sa.Column('kgs', sa.INTEGER(), nullable=True))
    op.drop_column('t_user_trainings', 'kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user_trainings', sa.Column('kg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('t_user_trainings', 'kgs')
    # ### end Alembic commands ###
