"""empty message

Revision ID: a4d75c1ca4b4
Revises: f9aaf73013f9
Create Date: 2024-02-02 18:20:53.150624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d75c1ca4b4'
down_revision: Union[str, None] = 'f9aaf73013f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_event', sa.Column('event_comment', sa.VARCHAR(length=100), nullable=True))
    op.add_column('m_part', sa.Column('sub_part_name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('m_part', sa.Column('part_comment', sa.VARCHAR(length=100), nullable=True))
    op.add_column('m_purpose', sa.Column('purpose_comment', sa.VARCHAR(length=100), nullable=True))
    op.add_column('m_trainings', sa.Column('purpose_id', sa.INTEGER(), nullable=True))
    op.drop_constraint('m_trainings_purpose_fkey', 'm_trainings', type_='foreignkey')
    op.create_foreign_key(None, 'm_trainings', 'm_purpose', ['purpose_id'], ['purpose_id'])
    op.drop_column('m_trainings', 'purpose')
    op.add_column('m_type', sa.Column('type_comment', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_type', 'type_comment')
    op.add_column('m_trainings', sa.Column('purpose', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'm_trainings', type_='foreignkey')
    op.create_foreign_key('m_trainings_purpose_fkey', 'm_trainings', 'm_purpose', ['purpose'], ['purpose_id'])
    op.drop_column('m_trainings', 'purpose_id')
    op.drop_column('m_purpose', 'purpose_comment')
    op.drop_column('m_part', 'part_comment')
    op.drop_column('m_part', 'sub_part_name')
    op.drop_column('m_event', 'event_comment')
    # ### end Alembic commands ###
