"""empty message

Revision ID: a7df352c8d81
Revises: aa06fc18c282
Create Date: 2024-02-13 10:10:07.773648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7df352c8d81'
down_revision: Union[str, None] = 'aa06fc18c282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_user_trainings_training_plan_id_fkey', 't_user_trainings', type_='foreignkey')
    op.create_foreign_key(None, 't_user_trainings', 't_training_plans', ['training_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user_trainings', type_='foreignkey')
    op.create_foreign_key('t_user_trainings_training_plan_id_fkey', 't_user_trainings', 't_training_plans', ['training_plan_id'], ['id'])
    # ### end Alembic commands ###
