"""empty message

Revision ID: aa06fc18c282
Revises: 2031a9c5d087
Create Date: 2024-02-05 15:57:51.680454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa06fc18c282'
down_revision: Union[str, None] = '2031a9c5d087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_notifications', sa.Column('animation_link', sa.VARCHAR(length=255), nullable=True))
    op.add_column('t_notifications', sa.Column('animation_width', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_notifications', 'animation_width')
    op.drop_column('t_notifications', 'animation_link')
    # ### end Alembic commands ###
