"""empty message

Revision ID: bd7956a6f409
Revises: 
Create Date: 2024-01-24 15:49:17.523881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7956a6f409'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_difficulty',
    sa.Column('difficulty_id', sa.INTEGER(), nullable=False),
    sa.Column('difficulty_rank', sa.INTEGER(), nullable=False),
    sa.Column('difficulty_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('difficulty_id')
    )
    op.create_table('m_effectiveness',
    sa.Column('effectiveness_id', sa.INTEGER(), nullable=False),
    sa.Column('effectiveness_rank', sa.INTEGER(), nullable=False),
    sa.Column('effectiveness_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('effectiveness_id')
    )
    op.create_table('m_event',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('m_part',
    sa.Column('part_id', sa.INTEGER(), nullable=False),
    sa.Column('part_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('m_prefectures',
    sa.Column('prefecture_id', sa.INTEGER(), nullable=False),
    sa.Column('prefecture_name', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('prefecture_id')
    )
    op.create_table('m_purpose',
    sa.Column('purpose_id', sa.INTEGER(), nullable=False),
    sa.Column('purpose_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('purpose_id')
    )
    op.create_table('m_type',
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('t_notifications',
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('detail', sa.TEXT(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_trainings',
    sa.Column('training_id', sa.INTEGER(), nullable=False),
    sa.Column('training_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('purpose', sa.INTEGER(), nullable=True),
    sa.Column('part_id', sa.INTEGER(), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=True),
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('effectiveness_id', sa.INTEGER(), nullable=True),
    sa.Column('difficulty_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['m_difficulty.difficulty_id'], ),
    sa.ForeignKeyConstraint(['effectiveness_id'], ['m_effectiveness.effectiveness_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['m_event.event_id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['m_part.part_id'], ),
    sa.ForeignKeyConstraint(['purpose'], ['m_purpose.purpose_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['m_type.type_id'], ),
    sa.PrimaryKeyConstraint('training_id')
    )
    op.create_table('t_users',
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tel', sa.VARCHAR(length=100), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('prefecture_id', sa.INTEGER(), nullable=True),
    sa.Column('point_possessed', sa.INTEGER(), nullable=False),
    sa.Column('id_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.ForeignKeyConstraint(['prefecture_id'], ['m_prefectures.prefecture_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('t_training_plans',
    sa.Column('training_plan_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('planned_user_id', sa.INTEGER(), nullable=True),
    sa.Column('training_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.ForeignKeyConstraint(['planned_user_id'], ['t_users.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['m_trainings.training_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_training_plans')
    op.drop_table('t_users')
    op.drop_table('m_trainings')
    op.drop_table('t_notifications')
    op.drop_table('m_type')
    op.drop_table('m_purpose')
    op.drop_table('m_prefectures')
    op.drop_table('m_part')
    op.drop_table('m_event')
    op.drop_table('m_effectiveness')
    op.drop_table('m_difficulty')
    # ### end Alembic commands ###
