"""empty message

Revision ID: f9aaf73013f9
Revises: dc3f7a6e512b
Create Date: 2024-02-01 01:08:20.335039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9aaf73013f9'
down_revision: Union[str, None] = 'dc3f7a6e512b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user_trainings',
    sa.Column('training_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('training_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.ForeignKeyConstraint(['training_id'], ['m_trainings.training_id'], ),
    sa.ForeignKeyConstraint(['training_plan_id'], ['t_training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('t_notifications', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 't_notifications', 't_users', ['user_id'], ['user_id'])
    op.add_column('t_training_plans', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('t_training_plans', sa.Column('training_plan_description', sa.TEXT(), nullable=True))
    op.drop_constraint('t_training_plans_planned_user_id_fkey', 't_training_plans', type_='foreignkey')
    op.drop_constraint('t_training_plans_training_id_fkey', 't_training_plans', type_='foreignkey')
    op.create_foreign_key(None, 't_training_plans', 't_users', ['user_id'], ['user_id'])
    op.drop_column('t_training_plans', 'training_id')
    op.drop_column('t_training_plans', 'planned_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_training_plans', sa.Column('planned_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('t_training_plans', sa.Column('training_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 't_training_plans', type_='foreignkey')
    op.create_foreign_key('t_training_plans_training_id_fkey', 't_training_plans', 'm_trainings', ['training_id'], ['training_id'])
    op.create_foreign_key('t_training_plans_planned_user_id_fkey', 't_training_plans', 't_users', ['planned_user_id'], ['id'])
    op.drop_column('t_training_plans', 'training_plan_description')
    op.drop_column('t_training_plans', 'user_id')
    op.drop_constraint(None, 't_notifications', type_='foreignkey')
    op.drop_column('t_notifications', 'user_id')
    op.drop_table('t_user_trainings')
    # ### end Alembic commands ###
